stages:
  - build  
  - test

build:
  image: maven:3.8-openjdk-11
  stage: build
  script:
    - mvn package -DskipTests=true

test:
  image: maven:3.8-openjdk-11
  stage: test
  script:
    - mvn clean test
